### ISSUE TITLE
PlatformException

### ISSUE THREAD

**Issue by RawadZogheib** [farmako/flutter_restart#10]
On one of my android devices I'm getting an exception but the plug-in keep working correctly!

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit', null, java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit'
E/flutter (23780): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/flutter (23780): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:61)
E/flutter (23780): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
E/flutter (23780): 	at app.farmako.restart.RestartPlugin.onMethodCall(RestartPlugin.kt:27)
E/flutter (23780): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (23780): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (23780): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (23780): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E/flutter (23780): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (23780): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (23780): 	at android.os.Looper.loopOnce(Looper.java:204)
E/flutter (23780): 	at android.os.Looper.loop(Looper.java:291)
E/flutter (23780): 	at android.app.ActivityThread.main(ActivityThread.java:8134)
E/flutter (23780): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23780): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
E/flutter (23780): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
E/flutter (23780): )
E/flutter (23780): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (23780): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (23780): <asynchronous suspension>
```

PS: This exception wasen't before we use this plugin.

**Comment by alexmercerind** [comment]
Hi! 

This is same as #7. I will publish an update on pub.dev, little short on time.

**Comment by RawadZogheib** [comment]
Okay thank you! waiting for the update!
Btw this plugin is amazing!!

**Comment by bziembanski** [comment]
Hi, this Platform Exception is still occurring with the latest version. Tested on release build it does restart application, but on debug this exception causes app to freeze
